{{- if not .Values.jwtSecret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fhir-server.jwtSecretName" . }}
  labels:
    {{- include "fhir-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.jwtSecret.value }}
  {{ .Values.jwtSecret.key }}: {{ .Values.jwtSecret.value | b64enc | quote }}
  {{- else }}
  {{ .Values.jwtSecret.key }}: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if and (not .Values.postgresql.enabled) (not .Values.externalDatabase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-external-db" (include "fhir-server.fullname" .) }}
  labels:
    {{- include "fhir-server.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
---
{{- if and .Values.config.grpc.tlsEnabled (not .Values.grpcTLS.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fhir-server.grpcTLSSecretName" . }}
  labels:
    {{- include "fhir-server.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.grpcTLS.cert | b64enc | quote }}
  tls.key: {{ .Values.grpcTLS.key | b64enc | quote }}
{{- end }}
