apiVersion: v1
kind: Service
metadata:
  name: {{ include "fhir-server.fullname" . }}-http
  labels:
    {{- include "fhir-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: http
  {{- with .Values.httpService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.httpService.type }}
  ports:
    - port: {{ .Values.httpService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fhir-server.selectorLabels" . | nindent 4 }}
